// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdv52gr1LAKZ9FIxqtzFW2NChEeln3m8o',
    appId: '1:1073179784206:web:1b985ea03b9a88a75f385f',
    messagingSenderId: '1073179784206',
    projectId: 'dospire-app',
    authDomain: 'dospire-app.firebaseapp.com',
    storageBucket: 'dospire-app.firebasestorage.app',
    measurementId: 'G-FZZZFVLQWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5KKmJ6KKmni7wcc_iqCf4x2WLkXNmfSA',
    appId: '1:1073179784206:android:ce4ceee387873e725f385f',
    messagingSenderId: '1073179784206',
    projectId: 'dospire-app',
    storageBucket: 'dospire-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8IrGeCWKy8dQ83tIVG5dfAk7DxA_h1f4',
    appId: '1:1073179784206:ios:91acc837927b10695f385f',
    messagingSenderId: '1073179784206',
    projectId: 'dospire-app',
    storageBucket: 'dospire-app.firebasestorage.app',
    iosBundleId: 'com.dospire.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8IrGeCWKy8dQ83tIVG5dfAk7DxA_h1f4',
    appId: '1:1073179784206:ios:1f1d7b9677cf57b65f385f',
    messagingSenderId: '1073179784206',
    projectId: 'dospire-app',
    storageBucket: 'dospire-app.firebasestorage.app',
    iosBundleId: 'com.example.dospire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdv52gr1LAKZ9FIxqtzFW2NChEeln3m8o',
    appId: '1:1073179784206:web:6d317d27bd4bc2fc5f385f',
    messagingSenderId: '1073179784206',
    projectId: 'dospire-app',
    authDomain: 'dospire-app.firebaseapp.com',
    storageBucket: 'dospire-app.firebasestorage.app',
    measurementId: 'G-M77XPNQLPG',
  );
}
